### ISSUE TITLE
Unlock session issue

### ISSUE THREAD

**Issue by semgmp** [digforit/platform#1]
---
name: **unlock session issue**
about: Unlock seesion not taking he right password if the first time a wrong password was typed.
title: 'Unlock session'
labels: ''
assignees: ''

---

**Describe the bug**
Session unlock issue "When a session password is created it work fine" but when i close the game and come back i am asked to put the session password, if for the first time i put a wrong password i will get a wrong password message, but when i put the right password the second time i still get wrong password

**To Reproduce**
1. Go to 'login with Tronlink'
2. Click on ' unlock session'
4. Put a wrong password the first time, and put the right password the second time 

**Expected behavior**
The password is supposed to be accepted and the session need to be restaured.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MAcOS Catalina]
 - Browser [chrome]
 - Version [ 79.0.3945.79]

**Smartphone (please complete the following information):**

**Additional context**
right password used: MINkapeu1006
Wrong password used : minkapeu1006

**Comment by digforit** [comment]
Resolved for v0.1.6
