### ISSUE TITLE
Black screen only music

### ISSUE THREAD

**Issue by Skandarn** [digforit/platform#10]
**Describe the bug**
After intro I choose digforit game. 
Screen goes down in tunnel music starts 
Blackscreen and only the arrow visible

It have worked before nothing changed on my part

**To Reproduce**

**Expected behavior**
To start the game

**Screenshots**

**Desktop (please complete the following information):**

Windows 10
Tronwalletplay latest
From this adress
TQEJbuEp8tgQ1mt9zuu5wNZgiXBeuxxEFX

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WardColeman** [comment]
KeyNotFoundException

![KeyNotFoundException](https://user-images.githubusercontent.com/59372847/71605733-e219fd00-2b30-11ea-9529-c860d79d1132.png)

**Comment by digforit** [comment]
Resolved for next version.
