### ISSUE TITLE
display/double gem in game map

### ISSUE THREAD

**Issue by njsantee** [digforit/platform#14]
**Describe the bug**
A gem is displaying over another in the same spot each time. It appears to count towards the chests as well. In the screen shots you can also see that the gem totals do not match the chest. There are 12 gems on the map but the chest counts 14. Maybe the two purple on the bottom are doubled (happening with blue gems as well)

**To Reproduce**
1. Go to the big game map and play through it using meteor
2. Refresh the big game map and grab the meteor tool and drop one before all of the tiles are replaced

**Expected behavior**
Should not display a gem over another

**Screenshots**

**Desktop (please complete the following information):**
 - Device: Computer
 - OS: WIN10
 - Browser: Chrome

**Additional context**
![image](https://user-images.githubusercontent.com/50242185/71607781-d420a800-2b41-11ea-9b96-f855ebd1e1e7.png)

![image](https://user-images.githubusercontent.com/50242185/71607858-95d7b880-2b42-11ea-9775-38668929eddd.png)
![image](https://user-images.githubusercontent.com/50242185/71608107-2d89d680-2b44-11ea-8f01-62e1d71b58e0.png)

**Comment by digforit** [comment]
This should have been resolved in milestone 0.1.6. Please reopen in other case.
