### ISSUE TITLE
Chest counters disappear when resizing window

### ISSUE THREAD

**Issue by njsantee** [digforit/platform#15]
**Describe the bug**
The chest counters disappear after resizing the game window and then returning to it.
**To Reproduce**
1. Go to map
2. Click on start digging
3. resize game window then go back in

**Expected behavior**
Counters should stay there

**Screenshots**
![image](https://user-images.githubusercontent.com/50242185/71609980-8eb8a680-2b52-11ea-8c72-87bfca94e317.png)

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser: TronWalletPlay

**Additional context**

**Comment by digforit** [comment]
* Resolved for milestone 0.1.6
