### ISSUE TITLE
freeze on provably fair screen

### ISSUE THREAD

**Issue by njsantee** [digforit/platform#17]
**Describe the bug**
the platform freezes when attempting to copy the nonce, client seed, server seed in the provably fair screen
**To Reproduce**
1. Go to provably fair screen
2. Click on copy nonce, local client seed, server seed
3. See error

**Expected behavior**
should not freeze

**Screenshots**
![image](https://user-images.githubusercontent.com/50242185/71610437-a42fcf80-2b56-11ea-813d-e28a0e2daad3.png)

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Browser TWP

**Comment by digforit** [comment]
This should be resolved on 0.1.6milestone.
