### ISSUE TITLE
Possible Features Added

### ISSUE THREAD

**Issue by ezr106** [digforit/platform#18]
Feature # 1- Logo on Gems
As you DIG in the map you have a brief pop up of what you won: TRX, DIG, SCC. I think it would be an attractive feature to add that logo to the GEMs in which you won, TRX, DIG, SCC. 
GEMs will get a great visual appeal when playing the game.

Feature # 2- Tier leveling Rewards
Add a reward as you level thru the tiers: Bronze, Silver, Gold, etc. Rewards maybe can consist of TRX, DIG, SCC, cost less to DIG the maps(1%-5%) or any suggestions from the community.

**Comment by digforit** [comment]
Adding logos to the gems will make the view unclean the way it is right now. We study it in the past and we have provided ways to see all the rewards obtained right now.

For the second part we'll research in the future for more uses to the level itself more than bragging.

Thank you for the suggestions.
