### ISSUE TITLE
Special and unique avatar

### ISSUE THREAD

**Issue by semgmp** [digforit/platform#2]
**Describe  feature**
A categories of avatar that the players can purchase through the platform that will be unique to them and no one else can have.

**Expected behavior**
Special avatar for premium players or for any player that can be purchased through the platform or can be earn by playing. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by digforit** [comment]
We have something planned, not milestoned yet.

**Comment by digforit** [comment]
Thank you for the suggestion.
