### ISSUE TITLE
Need for auto Play or to skip the select game board

### ISSUE THREAD

**Issue by bbryan927** [digforit/platform#22]
Possible auto play

The map should just reload to a new map at the end... Clicking play is getting repetitive

Like when I click the x to end a match that means I want to go play another

Atleast an option to auto play like that can be a button or check on the "select game board"

mining efficiency/ number of plays per hour matter... 

The easier and faster it is to keep pressing the buttons the more money digforit will make

People only have so much time to play games

**Comment by digforit** [comment]
Added basic skip the game board selection.
