### ISSUE TITLE
Bonus from rows of gems

### ISSUE THREAD

**Issue by Skandarn** [digforit/platform#23]
Here is something you should consider 
I think it would really improve the experience to

If you get 
3 gems in a row in one color it should count as 3 + 1
4 gems in a row should get +2
5 gems in a row should get +3

When I play and use the meteroite it is fun to spot patterns in the gems.  If you have Three in a row you will continue to find 4 or 5

This small feature would deepen the experience a lot

**Comment by digforit** [comment]
This is a very good idea that could improve the game. On the other hand it makes it more complex at some levels that doesn't worth the time right now + is more complex to understand to the user what is happening exactly.

Maybe we'll recover the issue in the future. Thank you for the suggestion.
