### ISSUE TITLE
No response when tiles are clicked

### ISSUE THREAD

**Issue by robtron2** [digforit/platform#24]
Test mode works on all boards, play mode does not work on any boards.  All play boards load as normal, any tools can be selected as normal, when a tile is selected there is no response.  Everything else functions as normal.  I have restarted the game, logged out and back in, restarted the computer, cleared the cache, with no luck in clearing the error.

**Comment by digforit** [comment]
This should have been resolved in 0.1.6 version. Reopen in case it happens again.
