### ISSUE TITLE
Holding SCC in wallet gives higher level

### ISSUE THREAD

**Issue by bbryan927** [digforit/platform#26]
What if you made each profile level dependent on experience -or- holding SCC in your wallet meaning you have to be holding a large amount of SCC to get Ruby perks 

It would put pressure on the exchanges and cause ppl to hold SCC as well.

Someone that owns 100k SCC in the wallet will be Ruby level in their profile right away instead of having to level up. Here's an example:

Silver = xp or holding 1000 SCC
Gold = xp or 5000 SCC
Emerald = exp or 25000 SCC
Sapphire = exp or 50000 SCC
Ruby. = exp or 100000 SCC

By buying SCC off the exchange early and holding would allow you to have better mining ability then just playing and earning your way up to better mining...

**Comment by digforit** [comment]
We have discussed this heavily but we found some problems to the idea (unbalanced experience).We'll try to find mechanism to mantain ppl holding SCC if needed but for now it's going to be mantained with exp points in game exclusively.
