### ISSUE TITLE
Token winnings are send to quick

### ISSUE THREAD

**Issue by MathijsBok** [digforit/platform#27]
**Describe the bug**
When you hit armageddon on the map then i see on notifications very quick what i win on that click. Instead of when the DIG action is ready. 

**To Reproduce**
1. Open Tronwallet app with wallet of play
2. Play map 10x10 and hit Armageddon button
3. Before Armageddon is ready you already see what you get.

**Expected behavior**
Summarize the winnings and after closing or ending map then send out the funds.

**Comment by digforit** [comment]
Extended time of reward withdrawal in 0.1.7
