### ISSUE TITLE
Able to win 100000 TRX in 10x10 map 

### ISSUE THREAD

**Issue by MathijsBok** [digforit/platform#28]
**Describe the bug**
Able to win 100.000 TRX in 10x10 map in map choice.

**Expected behavior**
Able to win 1.000.000 TRX in 10x10 map 

**Screenshots**
![Schermafbeelding 2020-01-18 om 00 15 49](https://user-images.githubusercontent.com/42490224/72652648-e2ffbb00-3987-11ea-987e-400bf57cf484.png)

**Comment by digforit** [comment]
Yes, it's in the list of updates whenever we finish a final fit for the numbers
