### ISSUE TITLE
TRX balance now showing on Wallet side

### ISSUE THREAD

**Issue by semgmp** [digforit/platform#3]
**Describe the bug**
Bank wallet session doesn't show TRX in wallet 

**To Reproduce**
1. Go to 'Lucky Dig'
2. Click on 'BANK icon'
3. Check wallet section 
4. The TRX in wallet not showing on the wallet section even though TRX in wallet 

**Expected behavior**
The amount of TRX in wallet need to show in the wallet section 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
https://tronscan.org/#/address/TKnq1MVregWgdKqM8ezrSjykdQRPkZe6Ro 
Above is my wallet with few TRX not showing on the platform

**Comment by digforit** [comment]
Reviweing it deeply, the version tested was with test tokens. that's why it wasn't showing your real TRX.
