### ISSUE TITLE
[Feature] Multiple Error Messages

### ISSUE THREAD

**Issue by DomChris** [digforit/platform#31]
When clicking on a currently unrelease game icon an error message is shown indicating it will be launched in the future. Multiple clicks add the same error in to the error queue.
While multiple errors can be helpful to the user i believe we should limit the unique errors in the queue (possibly 3?) as the repeated errors can make playing the game unenjoyable.

**Comment by digforit** [comment]
While we could do this we still believe in user matureness a little bit. Maybe we resolve this in the future. But for now we'll consider it not a bug.
