### ISSUE TITLE
[BUG] Warning shown in console on page load

### ISSUE THREAD

**Issue by DomChris** [digforit/platform#32]
2 Information advisory messages shown on initial site load

**To Reproduce**
1. Go to beta.digforit,win
2. read console messages

**Expected behavior**
The messages are not errors but advisory messages relating to deprecated functions

**Screenshots**
![image](https://user-images.githubusercontent.com/15716512/72664004-14649f00-39f9-11ea-9080-4fbc35b06ea1.png)

**Source**
 - Device: PC
 - OS: Windows 10 pro 64 bit
 - Browser Chrome
 - Version 79.0.3945.117

**Comment by digforit** [comment]
Resolved the visible warnings for 0.1.9
