### ISSUE TITLE
[BUG] Error in console

### ISSUE THREAD

**Issue by DomChris** [digforit/platform#33]
**Describe the bug**
Error shown in console advising of a deprecated function writeStringToMemory

**To Reproduce**
1. Load beta.digforit.win
2. Read console

**Expected behavior**
A page to load without error - there is no observable impact to page loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/15716512/72664056-b3899680-39f9-11ea-9ac3-b10097bf4c71.png)

**Source**
 - Device: PC
 - OS: Windows 10 pro 64bit
 - Browser Chrome
 - Version 79.0.3945.117

**Comment by digforit** [comment]
Solved for 0.1.9
