### ISSUE TITLE
[BUG] 10x10 500 DIG chest prize 

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#35]
**Describe the bug**
I played a game on the 10x10 map and I won the 500 DIG chest prize but it appear added to the dropped DIG.

**To Reproduce**
1. Go to '10x10'
2. win '500 Dig chest'
3. look wallet

**Expected behavior**
I expect the prize to be directly loaded into my wallet when game finished, with a separate note and not added to Dig's winnings

**Source**
 - Device: Pc
 - OS: windows 10
 - Browser chrome 
 - Browser Version 79.0.3945.117
 - Platform Version v0.1.7-beta

**Comment by digforit** [comment]
Despite the fact that would be more clear to the user. Looking at the big draw of the platform it's healthier to not start putting reward tickets per each micro-game . Each bet has it's result including chests or whatever other rewards can be given. The only difference would be when it's another token.

Then for now at least this will be to not fix. Thank you for the suggestion anyway.
