### ISSUE TITLE
[FEATURE] Mining mode 10x10

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#36]
In the 10x10 map, being a "premium" map you could consider the idea of ​​inserting the "mining mode" (for miners who want to leave in autoplay)

**Describe the solution you'd like**
"mining mode" available only on the 10x10 map, it provides an autostart of the game and the automatic use of meteorites. in this way the player can move away from the screen and leave the game automatically. very convenient for SCC miners

**Describe alternatives you've considered**
Below, in addition to the key to change the map before finishing it (dig game board) I would add two circular arrows to directly reset the map without entering the pop up page with all the other modes

**Additional context**
A separate payment may be required to activate this mode. By purchasing this mode only for a limited period of time (e.g. 1000 trx for 1 day of use)

**Comment by digforit** [comment]
We have consider the idea to make botable the game. But the time required now for that feature would be more than we are able to put in that one now. Maybe our priorities change in the future.

I understand to the discard functionality. The only problem I see is that functionality encourage the discard of the maps which is not the main aim of the platform. For now we'll mantain as it is and will review it if we see more feedback like yours in a future.

Thank you for your suggestion.
