### ISSUE TITLE
[FEATURE] Animation

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#37]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I remove the animations, but those related to the destruction of a square remain.

**Describe the solution you'd like**
speed up the interaction between animation and clicks or totally eliminate animations (prefer this).I understand the intention of wanting to keep the animations on the game because they are captivating, but I suppose that those who want to remove the animations have a PC that is not suitable for maintaining such high graphics or does it to speed up the game, removing this animation could favor the fluidity of the game . I myself, not having a powerful PC, would prefer not to see the animations.

**Comment by digforit** [comment]
Resolved for next milestion.
