### ISSUE TITLE
[FEATURE] empty tiles

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#38]
**Is your feature request related to a problem? Please describe.**
playing on the 3x3 map I noticed that it is a bit immature as many tiles are empty

**Describe the solution you'd like**
I believe that empty tiles could be replaced with tiles containing brown or gray / white stones, worthless

**Comment by digforit** [comment]
We think it's better to not add more noise to the maps, this way it's a little more honest to the player but less confusing. Thank you for the suggestion.
