### ISSUE TITLE
[FEATURE] names in evidence

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#39]
**Is your feature request related to a problem? Please describe.**
when I play I would like to see below the name of the tools that I want to use when I hover over it, with a miniaturized description about what it does. 
I'd like to see the tag when I put the cursor on the settings button and on all the tools on the side (chat, auction and so on)

**Comment by digforit** [comment]
We like to minimize hiden information and show the exclusive necesary info. We want to encourage players to play test and touch every button to see how it works but trying to be as simple as posible.

This is in line with the fact that more wordy platform means more translations and more error prone to misslead the player.

Thank you in advance for the suggestion.
