### ISSUE TITLE
Not able to purchase DIG token while having TRX 

### ISSUE THREAD

**Issue by semgmp** [digforit/platform#4]
**Describe the bug**
When i try to purchase DIG token through the platform even though  i have TRX it i get the error message "Buy Error : You don't have enough TRX to execute that buy" 

**To Reproduce**
1. Go to 'Lucky DIG'
2. Click on 'Store', Click on "custom" put the amount of DIG you want to buy, Click on " the amount on the texbox" at the buttom
4. See error "Buy Error : You don't have enough TRX to execute that buy" 

**Expected behavior**
The amount of DIG should be purchased and available in the Wallet.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS Catalina]
 - Browser [Chrome]
 - Version [ 79.0.3945.88 ]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by digforit** [comment]
This error comes cause other wallet has been loaded after login with an extension. This is controlled in the removal of session save for extensions plus an extra control in the buy actions.
