### ISSUE TITLE
[BUG] nickname 

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#40]
**Describe the bug**
I tried to change my nickname and noticed that a large number of letters could be entered. After entering many letters my nick remains the same "Diggy46" in my case. I believe that a physical limit should be placed on the letters that can be entered

**To Reproduce**
1. Go to 'profile.'
2. Click on 'nickname '
3. Try change name

With a normal amount of letters, it s all ok but with more letters like 20 the site return at the default nickname.

**Source**
 - Device: PC
 - OS: windows
 - Browser chrome 
- Browser Version 79.0.3945.117
- Platform Version v0.1.7-beta

**Additional context**
Just first time nickname can be changed as free, next time they must spend trx for that

**Comment by digforit** [comment]
Yes, there is a server limit of 20 characters. By error it was not limited in the client. Now the limit has been forzed in version 0.1.8
