### ISSUE TITLE
tiles under smoke lacking sides

### ISSUE THREAD

**Issue by JohnnyButcher** [digforit/platform#41]
minor visual comment, the three tiles under the smoke are lacking perspective (sides) also I find the floating tile more of a distraction than adding to the visuals
![image](https://user-images.githubusercontent.com/56912929/72675347-fae15700-3acd-11ea-90a9-1c57a84ed40a.png)

**Comment by digforit** [comment]
It happened to you always? I haven't been able to reproduce it, could you please attach more information and check if it's still happening to you?

**Comment by digforit** [comment]
closed until more info about this is provided.

**Comment by JohnnyButcher** [comment]
> It happened to you always? I haven't been able to reproduce it, could you please attach more information and check if it's still happening to you?

yes, it is still happening. not sure what else I could attach, what you see in the image is what I see this end. Maybe post in the beta testers room and ask if others are seeing this.
