### ISSUE TITLE
[FEATURE] highlight wins so they are more intoxicating 

### ISSUE THREAD

**Issue by JohnnyButcher** [digforit/platform#44]
maybe the stats for the round that appear in the top left could last a little longer and have a super exciting sound as they appear

Slot machine noises can be annoying but there is a lot of research behind why they use them

I just won 15500 TRX from the board and it wasn't really noticeable without full concentration

**Comment by Zaxxon67** [comment]
Agreed. High wins should be 'in your face' .... popups, bells, whistles, turds....whatever. But these high wins shouldn't go unnoticed

**Comment by digforit** [comment]
We are trying to power up a little bit table rewards. We know it's not going to be a definitive solution but will be near to give the required degree of importance.

This is dealing with the counterpart to try to stop the player as less as posible. Not an easy balance.

**Comment by digforit** [comment]
Added some extra emphasis on big tile rewards.
