### ISSUE TITLE
[BUG] Game Stats issue

### ISSUE THREAD

**Issue by njsantee** [digforit/platform#46]
**Describe the bug**
When entering the game stats page after having just switched to the day level and then left it shows the sum of all stats rather than just the day
**To Reproduce**
1. Go to the stats page and switch to the day level
2. leave the stats page
3. go back to the stats page
4. day level in slider is selected but the stats displayed are the sum

**Expected behavior**
should display the day stats

**Screenshots**

![image](https://user-images.githubusercontent.com/50242185/72675958-69340400-3a51-11ea-97ee-b7e194642957.png)

**Source**
 - Device: PC
 - OS: WIN 10
 - Browser: Tron Wallet Desktop
 - Browser Version:latest version
 - Platform Version: v0.1.7.1-beta

**Additional context**

**Comment by digforit** [comment]
Resolved for 0.1.8
