### ISSUE TITLE
[FEATURE] Screenshot prompt for 100k and 1mm chests

### ISSUE THREAD

**Issue by njsantee** [digforit/platform#47]
**Is your feature request related to a problem? Please describe.**
I would love a way to screenshot the chests in game when I win

**Describe the solution you'd like**
When a 100k or 1mm (maybe even 10k) chests are hit it would be great to get a "Share with your friends" pop up with a screenshot and a cheesy Diggy smile or something

**Describe alternatives you've considered**
Screenshot tool in windows

**Comment by digforit** [comment]
This is a very good idea. But this would fit better with mobile and we'll check this again in the future Thank you for the suggestion.
