### ISSUE TITLE
[FEATURE] Rewards ticker in top left corner that can be user reset

### ISSUE THREAD

**Issue by njsantee** [digforit/platform#48]
**Is your feature request related to a problem? Please describe.**
It is difficult to keep track of winnings in game because the thing in the top corner disappears

**Describe the solution you'd like**
A tracker that keeps tracking until the user resets it

**Describe alternatives you've considered**
checking bank after every game

**Additional context
Token      Amount
SCC             200
TRX             65 342
DIG              505 231
        RESET

**Comment by digforit** [comment]
We have resolve to create something similar showing bank in real time. This will be ready for 0.1.8
