### ISSUE TITLE
[FEATURE] maps name

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#49]
**Is your feature request related to a problem? Please describe.**
when I enter the game, I expect to find something that will encourage me to play more

**Describe the solution you'd like**
I think it's nicer to name the maps based on the level of "excavation" for which you play. 
Instead of:
 3x3 -> Tiny digger
5x5 -> Miner
10x10 -> Treasure hunter

**Additional context**
There is already an image and a description below that explains everything about the game! I think naming the map makes it much more beautiful and makes you feel part of the game even more

**Comment by digforit** [comment]
We like the idea, but fights with the idea to mantain UI as simple as posible to avoid extra noise. We are for the narrative in games to make them more beautiful. We'll review it in case we remade the interface for that reason. Thank you for your suggestion.
