### ISSUE TITLE
Seed logo not showing "BANK"

### ISSUE THREAD

**Issue by semgmp** [digforit/platform#5]
**Describe the bug**
The SEED logo is not showing when click on BANK logo, TRX and SCC are showing a logo 

**To Reproduce**
1. Go to 'Lucky DIG'
2. Click on ' BANK icon'
4. Seed logo now showing

**Expected behavior**
All token showing in that section need to have their logo or icon showing.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by digforit** [comment]
It's a default mechanism whenever the system doesn't found a token. Only promotional tokens should appear in production .
