### ISSUE TITLE
[FEATURE] game-in-game jackpot 

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#50]
**Is your feature request related to a problem? Please describe.**
when I dig I am happy to be able to compete with other miners not only for the ranking but also to win an alternative jackpot

**Describe the solution you'd like**
I'd like to drop letters hidden under a tile to compose the word: DIG FOR IT
Each letter will be dropped with a different probability, same with a very low probability. Whoever completes "dig for it" will receive part of the jackpot accumulated with the TRX played by  the players.

**Additional context**
You could insert a sort of auction where players can sell the rarest letters in exchange for SCC, half of the SCC spent on a letter will be burned and the other half will be given to the player who sold the letter

**Comment by digforit** [comment]
We have something planned in the future relative to this. Thank you for the suggestion.
