### ISSUE TITLE
[FEATURE] tempted play more

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#51]
**Is your feature request related to a problem? Please describe.**
I'd like to encourage kids to break all the tiles even after opening a chest.

**Describe the solution you'd like**
A prize could be given in Dig for each additional gem found in addition to the chest. 
3x3 map 50 dig each gem over 6 
5x5 map 100 dig each extra gem
10x10 map 200 dig per extra gem

**Additional context**
If I play by breaking one tile at a time and I win a chest, I am tempted to complete the map to win an additional bonus.

**Comment by digforit** [comment]
It's a good idea. The only problem I see is how to explain it visually. For now we'll mantain it this way, in the future we'll review any improvement of that deep if we see current system doesn't work properly.
