### ISSUE TITLE
Minor issues and gameplay ideas

### ISSUE THREAD

**Issue by jacobehrgott** [digforit/platform#53]
Dig for it notes

“Levels” page is confusing. Eventually figured it out but dunno why there’s a uSCC then converted would be simpler to understand just pre convert it and write that

Taskbar blocks part of game. Have to remove taskbar for smooth experience when most people will have it.

The special action buttons should have tooltips denoting what they do. It does explain in the website but it should be intuitive tooltip like all games.

The blow up 50 option needs to summarize the rewards of that blow up somewhere visible immediately on screen. 

Level system should be fleshed out. If your high level and speak in chat it should show your level maybe have a different color etc etc people love that stuff.

A cool feature would be like a .1 or .01% chance or something to spawn a “free” board or a board with some other cool feature. All the tiles could be Poo tiles or something with some accompanying music

**Comment by digforit** [comment]
Some of those has been resolved. Anyway please write sugestions 1 per issue . whenever something graphic is needed please provide screenshot. Thank you.
