### ISSUE TITLE
[BUG] occasional error when trying to buy dig

### ISSUE THREAD

**Issue by TronGuy33** [digforit/platform#56]
**Describe the bug**
After playing for a few hours I started to encounter a bug where the first time I try 

**To Reproduce**
1. Try to buy dig
2. Error occurs 
3. Retry to buy dig
4. Successful transaction

**Source**
 - Device: PC
 - OS: Windows 10
 - Browser: chrome
 

**Additional context**
 Just started happening after hours of constant play. Has happened 3 times now

**Comment by digforit** [comment]
This is a problem that we are having with TronLink . It seems a little intermitent but lately seems to be working ok. I'll reopen if problem persist.
