### ISSUE TITLE
[BUG] texts and link 

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#58]
**Describe the bug**
same texts and link issue

**To Reproduce**
1. Go to 'screen of to select map'
2. Click on '? (help button)'
3. Scroll down to 'how to play?'
4. See error 'Cost per tiles is incorrect

-------------------------------------
**To Reproduce**
1. Go to 'tournaments'
2. Click on '? (help button)'
3. See error '404 page not found'

--------------------------------------
**To Reproduce**
1. Go to 'statistics'
2. Click on '? (help button)'
3.  See error '404 page not found'

-------------------------------------
**To Reproduce**
1. Go to 'screen of to select map'
2. look 'maps description'
3. See error 'maximum payout per tile' 
3x3 2000trx 
5x5 7500trx 
10x10 15000trx

**Comment by digforit** [comment]
Solved for 0.1.9
