### ISSUE TITLE
[FEATURE] Extra button that wipes the current board

### ISSUE THREAD

**Issue by Zaxxon67** [digforit/platform#59]
Starting a clean board always takes 2 mouse clicks. I want to clean the board when the chests aren't holding enough gems. The current button (board with red cross) brings you back to the board menu. Then you have to press the play button again. 

It would be great to have an extra button that wipes the current board immediately.
This save a lot of time and an extra mouse click.

![2020-01-22 22_09_42-Microsoft Edge](https://user-images.githubusercontent.com/60200060/72937031-a60d3d00-3d68-11ea-9f94-9566e930e2e5.png)

**Comment by digforit** [comment]
We have added some mechanisms to simplify it the discoverying of the map. At some point the system is more focus in players joyness than fast discovering (mining run). We need to discard this functionality for that reason.

Anyway a way to speed up it you can disable animations. Thank you for your suggestion anyway.
