### ISSUE TITLE
DIG for IT chat not showing right number of online people

### ISSUE THREAD

**Issue by semgmp** [digforit/platform#6]
**Describe the bug**
The number of online people on the platform doesn't display the right number of actual people connected to the chat.

**To Reproduce**
1. Go to 'Lucky Dig'
2. Click on 'The chat icon'
3. Scroll down to ' number online'
4. The number show 6 all the time.

**Expected behavior**
That section is supposed to show the right amount of the people available on the chat.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by digforit** [comment]
this has been resolved in next beta.
