### ISSUE TITLE
[FEATURE] Dynamic stakes on 10*10 board

### ISSUE THREAD

**Issue by Zaxxon67** [digforit/platform#60]
The stakes gap between board 5 x 5 and board 10 x 10 is quite big for the average player. On the other hand, whales would like to be a bit more.

It would be a great improvement if the 10*10 board contains a windows for dynamic stake settings (from 30 - 50 DIG per tile). The setting will automatically adapt the prices. At a later stage the stakes could be configured higher (if the bank has enough liquidity).

**Comment by digforit** [comment]
For now we consider to mantain the game more simple. Other games will have more variance to let the player do that. Although it's a little rigid we prefer that to make the game more complex at this point. We'll review it in a future if we see it doesn't work properly.

Thank you for your suggestion.
