### ISSUE TITLE
Cannot Level Up To Ruby Max

### ISSUE THREAD

**Issue by WardColeman** [digforit/platform#61]
when leveling up from sapphire to ruby it leveled me up to sapphire... not ruby

restarted me on sapphire

![Screen Shot 2020-01-22 at 5 02 55 PM](https://user-images.githubusercontent.com/59372847/72942961-69c2e800-3d3a-11ea-99dc-fe1c5030c866.png)

**Comment by digforit** [comment]
It was a problem with decimals. Solved in 0.1.8
