### ISSUE TITLE
[BUG] select map tool

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#63]
**Describe the bug**
The tools to choose a different map must be pressed more than once to make it work

**To Reproduce**
1. Go to 'random map'
2. Click on 'tools to choose a different map'
3. More click to make it works

**Expected behavior**
One click to choose a different map.

**Source**
 - Device: pc
 - OS: windows 10
 - Browser chrome 
 - Browser Version 79.0.3945.117
 - Platform Version v0.1.8-beta

Sometimes I have the same problem with the play button

**Comment by digforit** [comment]
Solved for next milestone. Thank you.
