### ISSUE TITLE
[BUG] Bank view display issue

### ISSUE THREAD

**Issue by robtron2** [digforit/platform#64]
When playing with the bank view open there is an issue of balance not showing correctly.  When trx is won it displays a value of x2, when the board is complete it subtracts half of the value.  In the end the balance is correct, but leaves the feeling that the platform is taking funds from your account.  This issue is very noticeable on bigger wins, example, a player hits 15k trx, their bank balance goes up 30k trx, when games play is active again their balance goes down 15k trx giving them the correct win amount.

**Comment by Zaxxon67** [comment]
Example video. Second armageddon blast makes the TRX value go from 50500 TRX to 53000 TRX and jump to 55500 TRX. This number decreases back to 53000 TRX after the board is wiped.
[DIG_Trim.zip](https://github.com/digforit/platform/files/4112048/DIG_Trim.zip)

**Comment by digforit** [comment]
Solved for next milestone. Thank you.
