### ISSUE TITLE
Display total rewards to the right

### ISSUE THREAD

**Issue by learh** [digforit/platform#65]
**Is your feature request related to a problem? Please describe.**
I wish I could see the total I won on each board.

**Describe the solution you'd like**

in the new panel on the right, display the total numbesr of digs spent and the number of rewards.

examples:
-350 digs
+400 digs
+50 TRX
========
+50 digs
+50 TRX

**Comment by digforit** [comment]
The amount of information needs to be the neccesary. The UI needs to be as simple as posible and including that information will add more noise to the game itself right now.

We have provided different tools to calculate it. You have the bank preview and the bank history to check it.

Thank you for the suggestion anyway.
