### ISSUE TITLE
 activate all buttons on all board

### ISSUE THREAD

**Issue by learh** [digforit/platform#66]
**Is your feature request related to a problem? Please describe.**
I would like to have all the buttons (bombs, lightning, meteor, ...) on all the boars (3x3, 5x5). this way it's more funny

**Describe the solution you'd like**
Add all buttons on all boerds but in first time make them disabled.
Uou must then increase your ranking to activate them.

**Comment by digforit** [comment]
The effects are addapted to each map. Changuing it now would be difficult. Maybe we improve some of the tools like lighting.
