### ISSUE TITLE
[BUG] mistake translate in french

### ISSUE THREAD

**Issue by learh** [digforit/platform#68]
**Describe the bug**
mistake translate in french

**Expected behavior**
remove the 'e' in 'carrée". it's not correct in french

**Screenshots**
![Capture](https://user-images.githubusercontent.com/49024707/73123113-7d658d00-3f8c-11ea-8236-8f2647b507a7.JPG)

![Capture](https://user-images.githubusercontent.com/49024707/73123146-e1885100-3f8c-11ea-8d0c-1c367a03112c.JPG)

**Comment by digforit** [comment]
Solved for next milestone.
