### ISSUE TITLE
[BUG] wrong auction amount 

### ISSUE THREAD

**Issue by learh** [digforit/platform#69]
**Describe the bug**
the amount of auction is not correct 

**To Reproduce**
1. Go to 'Auction'
2. Auction with amount of 0.01 SCC
4. See error => display 0.0099999 SCC

**Expected behavior**
Auction with amount of 0.01 SCC

**Screenshots**
![Capture](https://user-images.githubusercontent.com/49024707/73123307-f1089980-3f8e-11ea-93ce-96f7daaaf5c2.JPG)

**Comment by digforit** [comment]
Solved for next milestone.
