### ISSUE TITLE
Profile display issue

### ISSUE THREAD

**Issue by njsantee** [digforit/platform#7]
**Describe the bug**
Display issue in the profile screen
**To Reproduce**
1. Open the profile screen.

**Expected behavior**
No display issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/50242185/71302037-3de3c980-236c-11ea-9817-a59790a606fb.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Comment by digforit** [comment]
It should be resolved next beta.
