### ISSUE TITLE
[BUG] Small glitch in token counter

### ISSUE THREAD

**Issue by Zaxxon67** [digforit/platform#76]
The token counter shows wrong (and sometimes a negative) DIG value for a short period of time.

Steps to reproduce:
1) Convert you TRX into DIG
2) Watch the token counter
3) Values also doesn't match the shop values

**Expected behavior**
Value should be correct and the same as shop values

**Screenshots**
![DigNegativeCounter](https://user-images.githubusercontent.com/60200060/73590785-c070b480-44e6-11ea-9c78-8d9d90f22998.jpg)

**Comment by digforit** [comment]
Trying to correct it requesting data if it detects a negative value.
