### ISSUE TITLE
[BUG] Reward board is visible while no board has been selected

### ISSUE THREAD

**Issue by Zaxxon67** [digforit/platform#79]
Reward board is visible while no board has been selected.

Haven't found a particular way to reproduce this issue.

**Expected behavior**
The reward board should only be visible while playing the boards.

**Screenshots**
![2020-02-01 15_42_46-Microsoft Edge](https://user-images.githubusercontent.com/60200060/73594172-fffdc780-450b-11ea-9b3e-ec9a50b5c4b9.png)

**Source**
3200*1800 screen resolution

**Comment by digforit** [comment]
Resolution issues on load
