### ISSUE TITLE
Emoji scrolling, and Scrolling in general on the platform

### ISSUE THREAD

**Issue by semgmp** [digforit/platform#8]
**Describe the bug**
Scrolling the emoji section on the chat is very fast, also scrolling the historical section, this make it almost impossible to choose the right emojii

**To Reproduce**
1. Go to 'Lucky DIG'
2. Click on 'Chat icon' and click on the Emoji below left side.
3. Scroll down to and see the how fast it goes

**Expected behavior**
The scrolling should be user friendly and allow people to scroll esasily

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by digforit** [comment]
Please add a video to check the exactly experience. In the meantime closing it.
