### ISSUE TITLE
[BUG] Reward board disappears or is aligned wrong while enabling fullscreen modus

### ISSUE THREAD

**Issue by Zaxxon67** [digforit/platform#80]
**Describe the bug**
The reward board disappears or is wong aligned while enabling full screen modus in Google Chrome.

**To Reproduce**
1. Use Shift + F11 within Chrome multiple times and see how the reward board is responding

**Expected behavior**
The reward board should stay visible and properly aligned.

**Screenshots**
No reward board.
![NoRewardBoard](https://user-images.githubusercontent.com/60200060/73594528-810a8e00-450f-11ea-9a64-8e520340f23b.png)

Not properly aligned reward board
![NotWellAlignedRewardBoard](https://user-images.githubusercontent.com/60200060/73594553-a5ff0100-450f-11ea-9676-dffa701dca6a.png)

Good aligned reward board
![ProperlyAlignedRewardBoard](https://user-images.githubusercontent.com/60200060/73594566-ba42fe00-450f-11ea-9d33-031a1a6952a9.png)

**Source**
3200*1800 screen resolution

**Comment by digforit** [comment]
duplicate #79 

it was the same bug.
