### ISSUE TITLE
Level points decreasing

### ISSUE THREAD

**Issue by MathijsBok** [digforit/platform#84]
**Describe the bug**
I have played 30-36 hours not, and my level status is decreased a lot. More then 50% And i was already in Smaragd 10%

Can you check those numbers since we have changed the play amounts.

![Schermafbeelding 2020-02-02 om 14 33 27](https://user-images.githubusercontent.com/42490224/73608983-57ae3880-45c9-11ea-86f7-fe3088a7be96.png)

**Comment by digforit** [comment]
Updated downgrading to 20% as we increase the hard of leveling up.
