### ISSUE TITLE
[BUG] double Auction issue 

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#87]
**1)**
**Describe the bug**
Should introduce a limit at sixth decimal of bid 

**To Reproduce**
1. Go to 'auction'
2. Click on 'insert your offert'
3. See error: you can bid Scc 0.00000001(8th decimal) 

---
**2)**
**Describe the bug**
After a bid of 0.000001 SCC i visualize 0 in the bid auction list

**To Reproduce**
1. Go to 'auction'
2. Click on 'insert your offert'
3. See error: you bid 0 Scc 

**Screenshots**
![Uploading 15811691743092731481630451388227.jpg…]()

**Comment by digforit** [comment]
Solved for next iteration.
