### ISSUE TITLE
[BUG] Auction bid time expired

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#88]
**Describe the bug**
when I do the auction and time runs out. I expect no more bets can be placed on that auction

**To Reproduce**
1. Go to 'auction'
2. Click on 'insert amount of Scc bid&burn'
3. Wait time runs out 
4. Place the bid

**Expected behavior**
transactions are rejected and no more bids can be placed on that auction

**Source**
 - Device: [ PC]
 - OS: [ windows 10]
 - Browser [chrome]
 - Browser Version [79.0.3945.130]
 - Platform Version [v0.2.0-beta]

**Comment by digforit** [comment]
Resolved in next iteration. to avoid using Dates, now it depends on server left time to make the calculations. (it should be more accurate.
