### ISSUE TITLE
[BUG] Help screen not properly aligned

### ISSUE THREAD

**Issue by Zaxxon67** [digforit/platform#89]
![Dig-Help01](https://user-images.githubusercontent.com/60200060/74089337-723c5200-4aa0-11ea-82f6-9734599fd3d1.png)

![Dig-Help02](https://user-images.githubusercontent.com/60200060/74089340-79fbf680-4aa0-11ea-817b-733b43e03378.png)

**Comment by digforit** [comment]
This has been solved in further versions
