### ISSUE TITLE
[BUG] can not log in with tronwallet onpc

### ISSUE THREAD

**Issue by robtron2** [digforit/platform#96]
When trying to log in on pc using tronwallet login link, my installed pc wallet is not found.  I have tried opening the game while logged into my desktop wallet and not logged into my desktop wallet.  When the tronwallet login link is clicked it takes me to the tronwallet page, with options to download the wallet.

![image](https://user-images.githubusercontent.com/59412456/74589028-54eb1480-4fc7-11ea-8c2a-baeae0a1ab18.png)

**Source**
 - Device: PC
 - OS: windows 10
 - Browser chrome
 - Browser Version Version 79.0.3945.130 (Official Build) (64-bit)
 - Platform Version v.0.2.6.3 prod

**Comment by digforit** [comment]
this is not a bug, tronwallet can only be executed from tronwallet aplications.
