### ISSUE TITLE
Decimal DIG sell

### ISSUE THREAD

**Issue by MathijsBok** [digforit/platform#98]
When you wanna sell DIG for TRX then it only works with whole numbers and no decimal numbers like 26.11111 but only with 26

![Schermafbeelding 2020-02-22 om 14 31 58](https://user-images.githubusercontent.com/42490224/75096354-1ba23e00-559f-11ea-8411-e30265f84e11.png)

**Comment by digforit** [comment]
Limited for next versions completetly to integer numbers for simplification.
